displayName=Prayer Alert
author=Ira Lee
description=Beeps while you attack an NPC with a combat style its overhead prayer protects against
tags=prayer,overhead,protect,combat,style,sound,alert,accessibility
plugins=com.github.ilee2.prayeralert.PrayerAlertPlugin
support=https://github.com/ilee2914/runelite_prayer_alert/issues
build=standard
